//Updated Jan 2023: Changed *Rec statements to all write to unique intersections


//This elimination occurs for GHI International entities in order to eliminate the profit on international entities at the consolidated level.  For balance sheet, the current and prior year profit/RE needs to be eliminated. For the PL, the CY net income needs to be eliminated.  The GHI Intl entities (less German Lab) are eliminated at 2 levels, the German lab is only eliminated at the GHI Inc level (due to the corp/legal entity structure layout). THIS ENTIRE SCRIPT LOGIC USES THE CYNI_ELIM DATASOURCE IN ORDER TO SEGREGATE THE CALCULATIONS.
// Calc for CYNI needs to occur first so there is data in the CYNI account for step 1.
// SELECT ALL CURRENCIES SO THAT RULES WILL RUN FOR ALL WHERE NECESSARY
*SELECT(%ALL_CURR%,[ID],RPTCURRENCY,"CALC = 'N' ")
 
// // Clears out CYNI_ELIM datasource to avoid duplication/build up of values
*XDIM_MEMBERSET DATASRC = BAS(EQUITY_ELIMS)
	*WHEN COCODE
      *IS *
*REC(FACTOR = 0)
   
   *ENDWHEN
*COMMIT
// IDENTIFY THE RETAINED EARNINGS FOR INT'L ENTITIES (LESS GERMAN LAB) AND ELIMINATE AT ELIM1 CO CODE, APPLY TO BALANCE SHEET ACCOUNTS
 
*XDIM_MEMBERSET COCODE = BAS(CO_TOTGHIINTL),CO_2541
*XDIM_MEMBERSET ACCOUNT = 330000,330001 
*XDIM_MEMBERSET RPTCURRENCY = LC,USD
*XDIM_MEMBERSET VERSION = %VERSION_SET%
*XDIM_MEMBERSET TIME = %TIME_SET%
 
*WHEN COCODE
      *IS CO_ELIM1,CO_ELIM2
		//skip
      *ELSE
		*REC(FACTOR = 1,ACCOUNT = 189000,TIME = %TIME_SET%,DATASRC = RE_ELIMS,COCODE = CO_ELIM2)
*REC(FACTOR = -1,ACCOUNT = 330001,TIME = %TIME_SET%,DATASRC = RE_ELIMS,COCODE = CO_ELIM2)
		
		*WHEN COCODE
			*IS CO_2541
				//skip
			*ELSE
				*REC(FACTOR = 1,ACCOUNT = 189000,TIME = %TIME_SET%,DATASRC = RE_ELIMS,COCODE = CO_ELIM1)
				*REC(FACTOR = -1,ACCOUNT = 330001,TIME = %TIME_SET%,DATASRC = RE_ELIMS,COCODE = CO_ELIM1)
		*ENDWHEN
*ENDWHEN
*COMMIT

 
// // //EXECUTE BUSINESS RULE FOR POSTING CURRENT YEAR NET INCOME TO THE BALANCE SHEET ACCOUNTS FOR ALL INT'L ENTITIES
//
*RUN_PROGRAM CALC_ACCOUNT
    CATEGORY = %VERSION_SET%
    CURRENCY = %ALL_CURR%
    TID_RA = %TIME_SET%
    COCODE = CO_2541,BAS(CO_TOTGHIINTL)
    CALC = CYNI
*ENDRUN_PROGRAM



//Calculates Current Year Net Inc for German Lab ONLY
*XDIM_MEMBERSET ACCOUNT = CYNI 
*XDIM_MEMBERSET RPTCURRENCY = LC,USD
*XDIM_MEMBERSET COCODE = CO_2541,BAS(CO_TOTGHIINTL)
*XDIM_MEMBERSET VERSION = %VERSION_SET%
*XDIM_MEMBERSET TIME = %TIME_SET%
//
//Uses cyni calc'd in ABOVE STEP and posts to ELIM2 CO CODE ONLY, BALANCE SHEET ONLY
//     
	*WHEN DATASRC
      *IS BAS(EQUITY_ELIMS)
		//skip
		*ELSE
			*REC(FACTOR = 1,DATASRC = CYNI_ELIM,ACCOUNT = 189000,COCODE = CO_ELIM2)
		
		*WHEN COCODE
			*IS CO_2541
				//skip
			*ELSE
				*REC(FACTOR = 1,DATASRC = CYNI_ELIM,ACCOUNT = 189000,COCODE = CO_ELIM1)
		*ENDWHEN
   *ENDWHEN
*COMMIT


// //CALCULATES THE NI FOR THE CURRENT MONTH GHI INTL ROLLUP GROUP TO APPLY TO PL EQUITY ACCOUNT FOR BOTH ELIM CO CODES
//CALCULATES THE NI FOR THE CURRENT MONTH GERMAN LAB CO CODE TO APPLY TO PL EQUITY ACCOUNT FOR ELIM2 CO CODE ONLY
//
*XDIM_MEMBERSET RPTCURRENCY = LC,USD
*XDIM_MEMBERSET VERSION = %VERSION_SET%
*XDIM_MEMBERSET TIME = %TIME_SET%
*XDIM_MEMBERSET ACCOUNT = BAS(PL_NI)
*XDIM_MEMBERSET COCODE = CO_2541,BAS(CO_TOTGHIINTL)
	*WHEN DATASRC
		*IS BAS(EQUITY_ELIMS)
			//skip
		*ELSE
			*REC(FACTOR = -1,DATASRC = CYNI_ELIM,ACCOUNT = 411000,COCODE = CO_ELIM2)
			
			*WHEN COCODE
				*IS CO_2541
					//skip
				*ELSE
					*REC(FACTOR = -1,DATASRC = CYNI_ELIM,ACCOUNT = 411000,COCODE = CO_ELIM1)
			*ENDWHEN
	*ENDWHEN
*COMMIT
