*SELECT(%ALL_CURR%,[ID],RPTCURRENCY,"CALC = 'N' ")
 
// // Clears out CYNI_ELIM datasource to avoid duplication/build up of values
 
*WHEN DATASRC
      *IS BAS(EQUITY_ELIMS)
     
        *REC(FACTOR = 0)
   *ENDWHEN
   *COMMIT
   //  // IDENTIFY THE RETAINED EARNINGS FOR INT'L ENTITIES (LESS GERMAN LAB) AND ELIMINATE AT ELIM1 CO CODE, APPLY TO BALANCE SHEET ACCOUNTS
 
*XDIM_MEMBERSET COCODE = BAS(CO_TOTGHIINTL),CO_2541 //added CO_2541
*XDIM_MEMBERSET ACCOUNT = 330000,330001 
*XDIM_MEMBERSET RPTCURRENCY = LC,USD
*XDIM_MEMBERSET VERSION = %VERSION_SET%
*XDIM_MEMBERSET TIME = %TIME_SET%
 
*WHEN COCODE
      *IS CO_ELIM1,CO_ELIM2
		//skip
      *ELSE
		*REC(FACTOR = 1,ACCOUNT = 189000,TIME = %TIME_SET%,DATASRC = RE_ELIMS,COCODE = CO_ELIM2)
        *REC(FACTOR = -1,ACCOUNT = 330001,TIME = %TIME_SET%,DATASRC = RE_ELIMS,COCODE = CO_ELIM2)
		
		*WHEN COCODE
			*IS CO_2541
				//skip
			*ELSE
				*REC(FACTOR = 1,ACCOUNT = 189000,TIME = %TIME_SET%,DATASRC = RE_ELIMS,COCODE = CO_ELIM1)
				*REC(FACTOR = -1,ACCOUNT = 330001,TIME = %TIME_SET%,DATASRC = RE_ELIMS,COCODE = CO_ELIM1)
		*ENDWHEN
*ENDWHEN
*COMMIT
//***IDENTIFY THE RETAINED EARNINGS FOR INT'L ENTITIES AND GERMAN LAB AND ELIMINATE ELIM2 CO CODE ONLY, APPLY TO BALANCE SHEET ACCOUNTS
 
*XDIM_MEMBERSET COCODE = BAS(CO_TOTGHIINTL),CO_2541
*XDIM_MEMBERSET ACCOUNT = 330000,330001 
*XDIM_MEMBERSET RPTCURRENCY = LC,USD
*XDIM_MEMBERSET VERSION = %VERSION_SET%
*XDIM_MEMBERSET TIME = %TIME_SET%
 
*WHEN COCODE
      *IS CO_ELIM2
      *ELSE
        *REC(FACTOR = 1,ACCOUNT = 189000,TIME = %TIME_SET%,DATASRC = CYNI_ELIM,COCODE = CO_ELIM2)
        *REC(FACTOR = -1,ACCOUNT = 330001,TIME = %TIME_SET%,DATASRC = CYNI_ELIM,COCODE = CO_ELIM2)
*ENDWHEN
*COMMIT
